import keyboard  # pip install keyboard
import time

def input_macro(key):
	keyboard.write(key)
	time.sleep(0.2)
	keyboard.send('enter')
	time.sleep(0.3)


time.sleep(5)


input_macro('Z')
input_macro('B')

input_macro('35')
input_macro('27')
input_macro('1')
input_macro('@')
input_macro('2')
input_macro('39')
input_macro('[')
input_macro('6')
input_macro(']')
input_macro('Hi')
input_macro('⭐')
input_macro('41')
input_macro('28')
input_macro('41')
input_macro('37')
input_macro('27')
input_macro('39')
input_macro('→')
input_macro('39')
input_macro('$')
input_macro('n')

input_macro('18')
input_macro('%Y-%m-%d %k:%M:%S')
input_macro('24')
input_macro('19')
input_macro('%!')
input_macro('n')

input_macro('13')
input_macro('55')
input_macro('13')
input_macro('55')
input_macro('21')
input_macro('45')
input_macro('16')
input_macro('55')
input_macro('9')
input_macro('53')
input_macro('35')
input_macro('19')
input_macro('49')
input_macro('4')
input_macro('54')
input_macro('28')
input_macro('251')
input_macro('71')
input_macro('8')
input_macro('39')
input_macro('25')
input_macro('50')
input_macro('27')
input_macro('55')
input_macro('13')
input_macro('55')
input_macro('13')
input_macro('55')
input_macro('13')
input_macro('55')
input_macro('55')
input_macro('19')
input_macro('55')
input_macro('55')
input_macro('17')
input_macro('55')

input_macro('14')
input_macro('44')
input_macro('4')
input_macro('52')
input_macro('10')
input_macro('34')

input_macro('Y')

# Allow for space for the scrollbar to go and not cover up the prompt
for i in range(8):
	input_macro(' ')
